services:
  - type: web
    name: ajk-website
    env: node
    plan: free
    buildCommand: npm install && npx tailwindcss -i ./src/styles.css -o ./dist/output.css --minify
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      # Required Environment Variables (set these in Render dashboard):
      # - ADMIN_EMAIL: Your admin panel login email (for authentication)
      # - ADMIN_EMAILS: Comma-separated list of admin emails for notifications (optional)
      #   Example: "sugampokharel28@gmail.com,Sanudhakal119@gmail.com"
      #   If not set, will use NOTIFICATION_EMAIL and default fallback
      # - NOTIFICATION_EMAIL: Single email for notifications (optional)
      # - ADMIN_PASSWORD: Your admin password
      # - ADMIN_USERNAME: Your admin username (default: admin)
      # - STRIPE_SECRET_KEY: Your Stripe secret key
      # - STRIPE_PUBLISHABLE_KEY: Your Stripe publishable key
      # - STRIPE_WEBHOOK_SECRET: Your Stripe webhook secret
      # - GEMINI_API_KEY: Your Google Gemini API key
      # Email Configuration (REQUIRED for email notifications):
      # - SMTP_HOST: SMTP server host (default: smtp.gmail.com)
      # - SMTP_PORT: SMTP server port (default: 587)
      # - SMTP_USER: Your Gmail address (e.g., your-email@gmail.com)
      # - SMTP_PASS: Gmail App Password (NOT your regular password!)
      # 
      # Gmail Setup Instructions:
      # 1. Enable 2-Factor Authentication on your Gmail account
      # 2. Generate an App Password: Google Account > Security > App passwords
      # 3. Use the App Password as SMTP_PASS (16 characters, no spaces)